import CartProvider from "./contexts/CartContext";
import { ProductsProvider } from "./contexts/ProductsContext";
import { UserProvider } from "./contexts/UserContext";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<UserProvider>
					<ProductsProvider>
						<CartProvider>{children}</CartProvider>
					</ProductsProvider>
				</UserProvider>
			</body>
		</html>
	);
}
